name: ParollService Api Build and Test .NET 4.6.1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET on version 4.6.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.6.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the Repository
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
